<h1> Contact us!</h1>
<p>We don't really want you to message any of us, so we'll provide you the information for our group leader instead!</p>
<a href="emailto:webmaster@koobkooc.net"/>webmaster@koobkooc.net</a> Here I think this will work...