<h1>Unit Tester</h1>
<h2>Ingredient Tests</h2>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'ch', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'salt', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'beer', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'nut', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'oil', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'br', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'egg', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'an', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'er', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'ol', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'bee', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'ca', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'to', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'or', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'oi', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'po', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'bu', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'ti', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'ro', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'pe', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', '', 1, TRUE));?></div>



<div class="run-tester"><?=site_url(array('search', 'ingredients', 'a', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'e', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'i', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'o', 1, TRUE));?></div>
<div class="run-tester"><?=site_url(array('search', 'ingredients', 'u', 1, TRUE));?></div>